theme = "identity"
disableKinds = ['taxonomy', 'term']
copyright = "2023 プロフィール.com"

baseURL = "https://プロフィール.com/aoba/"
title = "TLC | プロフィール.com"

[params]
author = "TLC"
icon = "aoba"
description = "PC/インフラ・ゲーム・気象・航空宇宙・写真・コーヒーなど・Enterpriseな機器や空が好き"

[[params.social]]
name = "twitter"
icon = "brands fa-twitter"
url = "https://twitter.com/intent/user?user_id=1115252417761689605"
